<section class="user-manager">
   <h2>INSCRIPTION</h2>
  <?php if ($this->error): ?>
   <p class="error">
    Il y avait un ou plusieurs des problèmes avec votre soumission.
    Corrigez-les S'il vous plaît comme Indiqué ci-dessous.
   </p>
   <?php endif ?>


    <?php
       $form = $this->form;
       $form->prepare();
       $form->setAttribute('action', $this->url(NULL, array('controller'=>'user-manager', 'action' => 'process')));
       $form->setAttribute('method', 'post');
       echo $this->form()->openTag($form);
    ?>

     <dl class="zend_form">
     <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
     <dd><?php
     echo $this->formElement($form->get('name'));
     echo $this->formElementErrors($form->get('name'));
     ?></dd>
     <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
    <dd><?php
     echo $this->formElement($form->get('email'));
     echo $this->formElementErrors($form->get('email'));
     ?></dd>
     
     <dd><?php
     echo $this->formElement($form->get('submit'));
     echo $this->formElementErrors($form->get('submit'));
     ?></dd>
     </dl>


     <?php echo $this->form()->closeTag() ?>
</section>



