 <?php
 // /users/user-manager/index.phtml:

 $title = 'Product';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo  $this->url('store', array('action'=>'add'));?>">Ajouter un produit</a>
 </p>

 <table class="table">
 <tr>
     <th> id</th>    
     <th>Name</th>
     <th>Description</th>
     <th>Cost</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($products1 as $product) : ?>
 <?php echo var_dump($product); ?>
 <tr>
    <td><?php echo $this->escapeHtml($product->id);?></td>
     <td><?php echo $this->escapeHtml($product->name);?></td>
     <td><?php echo $this->escapeHtml($product->desc);?></td>
     <td><?php echo $this->escapeHtml($product->cost);?> €</td>
     <td>
         <a href="<?php echo $this->url('store',
             array('action'=>'productDetail', 'id' => $product->id ));?>">Edit</a>
         <a href="<?php echo $this->url('store',
             array('action'=>'delete', 'id' => $product->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
