<?php

// Attached jQuery UI Scripts
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');

$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');
// Attach jQuery UI Styles
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');


// UI Initializer for buttons
$this->headScript()->appendScript('$(function() {
                $("a.ui-button").button();
                     });', 'text/javascript');

?>



<h1>Welcome to Users Module</h1>

<h2>Utilisateurs existants</h2>
<a href="/users/index/login" class='ui-button'>Login</a>

<hr>

<h2>Nouveaux utilisateurs </h2>
<a href="/users/index/register" class='ui-button'>New User Registration</a>