 <?php
 // /users/user-manager/index.phtml:

 $title = 'Users';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo  $this->url('user-manager', array('action'=>'add'));?>">Ajouter un Utilisateur</a>
 </p>

 <table class="table">
 <tr>
     <th> id</th>    
     <th>Name</th>
     <th>User ID/Email</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <?php echo var_dump($user); ?>
 <tr>
    <td><?php echo $this->escapeHtml($user->id);?></td>
     <td><?php echo $this->escapeHtml($user->name);?></td>
     <td><?php echo $this->escapeHtml($user->email);?></td>
     <td>
         <a href="<?php echo $this->url('user-manager',
             array('action'=>'edit', 'id' => $user->id ));?>">Edit</a>
         <a href="<?php echo $this->url('user-manager',
             array('action'=>'delete', 'id' => $user->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
